# Generated by Django 4.1.7 on 2023-02-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
